### ISSUE TITLE
Use of a Curseforge modpack that does not have a server pack

### ISSUE THREAD

**Issue by andreracz** [itzg/docker-minecraft-server#1035]
Is there a way to use a CF Modpack that does not have a server pack, and make it download all the mods?

I tried using CF_SERVER_MOD and MANIFEST, but always got an error that this is not a valid modpack.

If it does not work, can I try to implement it and make a PR?

**Comment by itzg** [comment]
No...but I just ripped out all of the code that did most of that

https://github.com/itzg/mc-server-runner/commit/cf93447fcc5f818831f462d5e92ebf77f570a06a

It still didn't account for all of the config file assets, etc. Since it turned out to be quite complicated, I didn't want a dormant feature lurking. 

You're welcome to revive and finish that feature out. Or I would be interested in a simpler, cleaner solution if you want to contribute that way.

**Comment by andreracz** [comment]
Thanks for the reply, I'll look into it. 
BTW, thanks a lot for this amazing project. I love it!

**Comment by itzg** [comment]
Thanks 😁

BTW I just realized I still have the invocation spot left in the image script

https://github.com/itzg/docker-minecraft-server/blob/27523a1c4557b6d9c2bc53e65af8d67a5541c856/start-minecraftFinalSetup#L184
