### ISSUE TITLE
Consider removing Mohist support

### ISSUE THREAD

**Issue by mq1** [itzg/docker-minecraft-server#1107]
Mohist seems to have malicious behaviours, check out these links

https://essentialsx.net/do-not-use-mohist.html
https://github.com/kennytv/list-of-shame

**Comment by itzg** [comment]
Thanks for bringing this to my attention. I'll strongly consider this and at a minimum include a warning and link to the PSA.

**Comment by itzg** [comment]
Added a caution statement at the start of https://github.com/itzg/docker-minecraft-server#running-a-mohist-server

**Comment by Shawiizz** [comment]
Hello, please know that Mohist is not malicious and that almost all of the information of the EssentialsX PSA is false or outdated. Please read https://github.com/Shawiizz/MohistEssentialsX/blob/main/README.md to understand more.

**Comment by itzg** [comment]
I didn't even want to get in the middle of this in the first place. EssentialsX seems like a credible source so I provide the info for users to decide. 

@Shawiizz I'm not sure who you are and why your information is authoritative. Can you please justify?

**Comment by Shawiizz** [comment]
I'm one of the Mohist's administrator, and I wrote the MohistEssentialsX readme because almost everything is false and outdated in the EssentialsX PSA. Even if EssentialsX seems to be a credible source, they do not know anything about Mohist. I think the PSA was created because they don't want to hear about hybrids servers, and to be honest i still don't really know why they wrote it.

**Comment by itzg** [comment]
Back to neutral ground: https://github.com/itzg/docker-minecraft-server#running-a-mohist-server
