### ISSUE TITLE
"copying between containers is not supported" when i'm copying from my hard drive to a volume

### ISSUE THREAD

**Issue by simon12mm** [itzg/docker-minecraft-server#1116]
### Describe the problem

I'm trying to import mods for my server, but running the command `docker cp focused_morse:/data/mods localhost/D:/mods` just returns `"copying between containers is not supported"`.
For context, the container is named "focused_morse", and the file i want to transfer is the "mods" folder located inside my D: drive.
I've looked online, but everything i try returns the same line.

### Container definition

The compose code is 
`version: "3"`

`services:`
  `mc:`
    `image: itzg/minecraft-server:java8`
    `ports:`
      `- 25565:25565`
    `environment:`
      `EULA: "TRUE"`
      `TYPE: "FORGE"`
      `VERSION: "1.16.5"`
      `FORGEVERSION: "36.2.8"`
      `DIFFICULTY: "normal"`
    `tty: true`
    `stdin_open: true`
    `restart: unless-stopped`
    `volumes:`
    `-/home/simon/minecraft/data:data`
And to create the container i ran "docker run -d -it -p 25565:25565 -e EULA=TRUE -e TYPE=FORGE -e VERSION=1.16.5 -e FORGEVERSION=36.2.8 itzg/minecraft-server:java8"

**Comment by itzg** [comment]
I'm not sure why you're reporting an issue against my image, when you have a docker usage question. In any case, I'll help you out:

Looking at

https://docs.docker.com/engine/reference/commandline/cp/#:~:text=A%20colon%20(%3A)%20is,or%20%60./file%3Aname.txt%60

it is getting confused since there's a colon in there. Also the `localhost/` is adding to its confusion. Why do you have that there? As a result, it thinks you're referring to a container named `localhost/D` and copying into a path `/mods` within that container. Try `D:\mods` instead.
