### ISSUE TITLE
Deprecate logstash and kibana images

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#130]
The ease of use of the official logstash image has now outweighed the cost of maintaining a separate one. As such, the one here in `dockerfiles` can be deprecated.

**Comment by ferronrsmith** [comment]
ok make sense. Thanks for the heads up!

**Comment by itzg** [comment]
@ferronrsmith ...however, were/are there features above and beyond the official ones you'd like? It later dawned on me that I could now build an image from theirs. Selfishly, I no longer needed my auto-plugin install feature since the two plugins I used were no longer applicable in 5.x.

**Comment by ferronrsmith** [comment]
Actually I try to stay away from plugins for kibana, because some clients don't allow installs inside their environment and since we don't always have control of the installs it's best just to worth with the default. 

I use the elasticsearch plugin mostly, in my `dev`, 'demo` and `production` environment. The official image doesn't do muli-node configuration with different node-type properly. (At least not to my liking)

**Comment by itzg** [comment]
Cool, multi-node config is the reason I spun off my own elasticsearch image, so I'm glad to hear that's the motivator for you also.

**Comment by ferronrsmith** [comment]
>A node that has node.ingest set to true (default). Ingest nodes are able to apply an ingest pipeline to a document in order to transform and enrich the document before indexing. With a heavy ingest load, it makes sense to use dedicated ingest nodes and to mark the master and data nodes as node.ingest: false. 

Seems like we now need to disable `node.ingest` for master nodes https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#master-node

**Comment by itzg** [comment]
...and add a new `NODE_TYPE` for ingest. I have to admit that the new beats aspect looks super cool, but I haven't yet used it.

**Comment by ferronrsmith** [comment]
Yea and I agree
