### ISSUE TITLE
WHITELIST method fails with Microsoft accounts

### ISSUE THREAD

**Issue by natewalck** [itzg/docker-minecraft-server#1436]
### Describe the problem

When using the `WHITELIST=USERNAMEHERE` method for for adding users to a white list, it will fail when the account is a Microsoft account.

For instance, I addd `fenox` to my whitelist as seen here:
```
      - WHITELIST=fenox
```

But when I log on, the server log says i've not been whitelisted:
```
[19:14:09 INFO]: UUID of player fenox is ebf6a9d0-2b3b-31ee-821b-492c1fc625b2
[19:14:10 INFO]: Disconnecting com.mojang.authlib.GameProfile@363d56a0[id=ebf6a9d0-2b3b-31ee-821b-492c1fc625b2,name=fenox,properties={},legacy=false] (/192.168.7.40:59334): You are not whitelisted on this server!
[19:14:10 INFO]: com.mojang.authlib.GameProfile@363d56a0[id=ebf6a9d0-2b3b-31ee-821b-492c1fc625b2,name=fenox,properties={},legacy=false] (/192.168.7.40:59334) lost connection: You are not whitelisted on this server!
```
If I instead take the UUID listed in the error, which is what the server believes my UUID to be and put that on the whitelist instead, I get a different error:

```
[init] Updating whitelist
[mc-image-helper] 19:17:45.304 ERROR : 'get' command failed: Failed to download https://playerdb.co/api/player/minecraft/ebf6a9d0-2b3b-31ee-821b-492c1fc625b2: status code: 500, reason phrase: Internal Server Error
[init] Checking for JSON files.
```

Sure enough, if you go to playerdb.co and put in `fenox` you get this:  https://playerdb.co/api/player/minecraft/fenox, which gives you a UUID that the server does *not* show in the logs at all.

But if you put in the UUID the server sees, it throws a 500:  https://playerdb.co/api/player/minecraft/ebf6a9d0-2b3b-31ee-821b-492c1fc625b2

It looks to me like playerdb is not handling mojang vs microsoft accounts as expected. 

To work around this, I ended up passing in the whole whitelist.json file as shown here, which works as expected:
```
[
  { "uuid": "ebf6a9d0-2b3b-31ee-821b-492c1fc625b2", "name": "fenox" }
]
```

### Container definition

See main description. All the data is there.

### Container logs

See main description. All the data is there.

**Comment by itzg** [comment]
Something strange is happening with your profile specifically. Both PlayerDB and Mojang's own API return `84a084c3c20d435ebcb4b326267653d3` as your UUID:
```
curl --request GET \
  --url https://api.mojang.com/users/profiles/minecraft/fenox
```

responds
```
{
	"name": "fenox",
	"id": "84a084c3c20d435ebcb4b326267653d3"
}
```

I am going to switch from PlayerDB to Mojang's API but your issue seems to be something else.

**Comment by natewalck** [comment]
That is definitely odd. I had this happen with everyone that tried to join 🤷 It was odd. 

I have offline true, if that matters.

**Comment by itzg** [comment]
Ah `ONLINE_MODE=false` seems to matter a lot. Another user reported a similar issue https://github.com/itzg/minecraft-server-charts/issues/116 . Providing the ops and whitelist files probably is the only solution at this point.

**Comment by finndo77** [comment]
from past experience, not sure if it is still valid with all the changes going on with Minecraft, the UUID for an offline user will be the same each time a user logs in, I believe, even if you delete the player data folder.  I used to have multiple servers in offline mode as only people on the local network had access, and when I needed to open them to people outside the local network, I had to rework my whitelists for the correct UUID.  The offline UUID was the same on all servers for the same players (I copied the whitelist file from one to the others and never had an issue).

Note that if you take an offline server and bring it online, then take it offline again, the UUID of players will flip back and forth each time.  This causes inventory loss if you do not rename the files in the playerdata folder (learned this the hard way, which lead me to look into it more, nothing inside the file needs to be changed, just the file name).

I am going from memory, so cannot 100% confirm this next part; however I do believe that different minecraft server types will generate different UUIDs (forge, fabric, spigot, paper...).  just an fyi if you run multiple types and also have some plugin/mod that syncs data between the servers as having a different UUID will prevent that sync from working correctly.

hope this info is helpful

**Comment by itzg** [comment]
It sounds like the OP was not a bug, but rather a complexity one must accept when using offline mode. With that said, should logic be added to disallow `ONLINE_MODE=false` and a container managed whitelist?

**Comment by finndo77** [comment]
They work together, what I did initially was to add both the online and the
offline UUID to the server. You can lookup the online of they are using
their real account name when playing, or just run the server in both modes
to capture the UUIDs in the logs.  Then add both to the whitelist, this
will allow log ins for either mode.

Also, since you have to restart the server to change between them, you
either need 2 launch scripts/compose, or manually edit it each time.

I'd recommend using a script to flip, you could use a temp empty file
created in the script as a way to decide which way to flip, or if you ate
not that good just make 2 scripts.

1. Online-to-offline
Which makes a backup of the playerdata file, then creates a new playerdata
folder and copies the player data over from the online UUID to the offline
UUID. Next the script would call the docker launch for offline mode
script/compose file (or use sed if you are on Linux to swap false for true.

2. Basically the reverse of the above

Then op can just run the one they need and everything will just work.  Only
requires the initially UUID gathering, which OP should already have from
running offline combined with a minecraft user lookup website.


As far as the docker image is concerned I think it works as it should,
unless you are using the variable override command it won't switch the
server between online and offline if you just edit your script/compose file
on accident, it has to be an intentional change.

**Comment by itzg** [comment]
Thanks for the clarification @finndo77
