### ISSUE TITLE
rcon-cli not working as of image 4/11/22

### ISSUE THREAD

**Issue by mhbates** [itzg/docker-minecraft-server#1472]
### Describe the problem

After my containers updated to the new image on 4/11, rcon-cli stopped working. I now get the following error:

`Failed to connect to RCON serverdial tcp 127.0.0.1:27015: connect: connection refused`

Subsequent image released on 4/12 has the same issue.

### Container definition

```
Paste run command or compose file here
```

### Container logs

```
Paste logs here
```

**Comment by CDFN** [comment]
I've done some testing and can confirm the issue. Such commands works just fine:
```
rcon-cli --port 25575 --password minecraft list
There are 0 of a max of 20 players online:
```
So I guess there was some change in either rcon-cli or Minecraft where port (and password?) got changed.

**Comment by CDFN** [comment]
It can be bug in docker image as that bug exists in older Minecraft versions. rcon-cli has no recent changes as well so my bet is it got introduced by mistake.

**Comment by itzg** [comment]
It's a bit of both. Since I removed the `RCON_PORT` env from the Dockerfile, then the default from rcon-cli was used. For some reason I totally don't remember, it's using 27015 as the default:

https://github.com/itzg/rcon-cli/blob/31e3809faafa159d92ede18342dfe74ca9fe716c/cmd/root.go#L79

I'm going to change the default over there since it is self-contracting its docs.
