### ISSUE TITLE
Failed to verify username

### ISSUE THREAD

**Issue by eosfor** [itzg/docker-minecraft-server#188]
Nubie question. After I start the image and connect I see the following messages in the log. Connection obviously fails with the same message. What do I do with them?

[10:43:22] [User Authenticator #5/ERROR]: Username 'Dad' tried to join with an invalid session
[10:43:22] [Server thread/INFO]: /172.17.0.1:60564 lost connection: Failed to verify username!

**Comment by itzg** [comment]
I believe at that stage the Minecraft server is trying to authenticate the user against a Mojang/Minecraft account; however, I’m not exactly sure how they do that since you log in via the client. The server seems to have an offline mode that might avoid that authentication step, but then that seems to easy of a loop hole :)

**Comment by jmorascalyr** [comment]
I am hitting this issue when i try to join with a bot. I am wondering if there is a config setting that will allow my bots to join.
