### ISSUE TITLE
AUTO_CURSEFORGE to support specific mods with disallowed distribution

### ISSUE THREAD

**Issue by FChapeau** [itzg/docker-minecraft-server#2067]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

I run an ATM8 server, which allows third party distribution. But within it, three mods (Hexerei, More Overlays Updated, Fix Experience Bug) disallow distribution, which cause them to be absent.

Is there a way to specify a download URL for the jar, or a way to provide the jars?

**Comment by itzg** [comment]
Since they disallow automated downloading you'll need to use one of these methods 

https://github.com/itzg/docker-minecraft-server#working-with-mods-and-plugins

**Comment by Kakoen** [comment]
I also ran into the same issue.

`The authors of the mod 'Hexerei' have disallowed project distribution. Manually download the file 'hexerei-0.3.0.jar' from https://www.curseforge.com/minecraft/mc-mods/hexerei and supply the mod file separately.`

In my cause the auto-update to the latest ATM8 modpack broke my server. Multiple mods were not installed, causing all kinds of issues at runtime.

The COPY_MODS_SRC option allows mod versions to differ from the mod pack when the server auto-updates the modpack. So I have a slightly different suggestion.

1. Add an option, say DOWNLOADED_MODS_SRC, that serves as a lookup for mods that cannot be downloaded automatically. Since it already knows the file name it is looking for, it could just copy it over from there.

2. Add the option to fail if the mod cannot be downloaded and/or copied from that directory, which instructions on downloading the mod and putting it there (basically the message you have now).

This would prevent the server to start up with wrong or missing versions of mods. And if you have multiple servers it could be a shared directory where mods are pulled from.

**Comment by itzg** [comment]
That's a great idea @Kakoen especially with introducing the separate designation of DOWNLOADED_MODS_SRC to avoid confusing users with the existing behavior of the "/mods" mechanism. I'll get this queued up.

**Comment by itzg** [comment]
Just thinking, I might make the new mechanism and it's variable a bit more CF centric. I'm thinking of calling it CF_DOWNLOADS_REPO and can contain all manner of CF files including not only mod jars but also the modpack zips. The latter are also sometimes marked by authors for non-distribution. I might also include support for optional subdirectories to allow for organizing files by type.
