### ISSUE TITLE
Minecraft - Spigot.yml

### ISSUE THREAD

**Issue by Stumblinbear** [itzg/docker-minecraft-server#248]
Do you think some environment variables for spigot.yml file settings could be added? I'm mostly looking for a `bungeecord: true` setting. I can add in a workaround for now to change the file, but it would be a useful feature to have.

**Comment by itzg** [comment]
That sounds like a good and feasible idea.

As a note to myself, here's the config file docs
https://www.spigotmc.org/wiki/spigot-configuration/

**Comment by Stumblinbear** [comment]
It would probably be best to prefix them all by `SPIGOT_` just to keep things separated, though I'm sure you were already going to do that. There are... a LOT of settings in the `spigot.yml` file, to be honest. I'd assist in adding them if I understood your whole setup and if I had the time.

As a side note, does PaperSpigot have some of its own configuration settings? Does Sponge? It may be a good idea to look into that at the same time so you don't need to in the future.

I really appreciate this resource, by the way. I've been working on a bungeecord/mc server clustering system in Kubernetes, and this is the minecraft image I've been using. ^^

**Comment by itzg** [comment]
Sorry for the silence, I have been continuing to think of this off and on. I'm thinking the image could bundle a `spigot.yml.template` file that would get processed with bash to do variable substitution such as:

```
bungeecord: ${SPIGOT_BUNGEECORD:-false}
```

...however, since you mention running this Kubernetes, it might be more effective to manage the spigot.yml as a ConfigMap entry and mount that into the container.

Speaking of Kubernetes, you might be interested in this tool I created that leverages service discovery to proxy and route incoming client connections:

https://github.com/itzg/mc-router#using-kubernetes-service-auto-discovery

**Comment by BadrBelhiti** [comment]
+1 on this request. I'd like to be able to `COPY` "override" files to `/data` without them being overwritten by the server on launch. I really want to just use `COPY` as opposed to volumes or platform-specific features like ConfigMaps in order to simplify productionization, and I think intuitively it just makes more sense for static configs to be baked into the image at build time.

The developer experience I envision is:
1. I create an override file (`overrides/spigot.yml`) with contents:
```yml
settings:
  bungeecord: true
```

2. I define my Dockerfile as:
```dockerfile
FROM itzg/minecraft-server:latest
...
COPY overrides /overrides
...
```

3. The final `spigot.yml` used by the server is the default with my overrides applied on top

I haven't thought too much about how to implement this yet, but I imagine we can merge `/data/spigot.yml` with `/overrides/spigot.yml` then restart the server with the final merged result. This can be easily extended to other config files as well. If we're fine with this approach and DX then I can have a crack at this PR.

**Comment by itzg** [comment]
There's already a couple of ways to take a file initially copied over from /config path and modify/patch those

https://docker-minecraft-server.readthedocs.io/en/latest/configuration/interpolating/

**Comment by BadrBelhiti** [comment]
Perfect, thanks! I was able to use this patch file to set `bungeecord: true`

```json
{
  "file": "/data/spigot.yml",
  "ops": [
    {
      "$set": {
        "path": "$.settings.bungeecord",
        "value": true
      }
    }
  ]
}
```
