### ISSUE TITLE
bukkit server error /start: line 10: eula.txt: Permission denied 

### ISSUE THREAD

**Issue by Pristar4** [itzg/docker-minecraft-server#264]
that is my run command docker run  -v /opt/mc/mc-felix:/data -e /opt/mc/mc-felix:/plugins -e /opt/mc/mc-felix:/Mods -e TYPE=BUKKIT -e  https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.13.2.jar -p 25566:25599 -e EULA=TRUE -e  INIT_MEMORY=1G -e MAX_MEMORY=16G  --name mc-felix itzg/minecraft-server

![problem](https://user-images.githubusercontent.com/42582409/49751043-bbcaba80-fcac-11e8-9abf-e063b31d0200.PNG)

**Comment by itzg** [comment]
It looks like a file permission issue; however, I’m not seeing the initial log message I expected for diagnosing those. Can you do a `docker pull itzg/minecraft-server` to ensure you’re using the latest image?

**Comment by x3rAx** [comment]
Just stumbled over this issue while searching for another one...

I had a similar issue after I enabled "[namespace remapping](https://docs.docker.com/engine/security/userns-remap/)" for the docker daemon (even though I saw some more logging information)

```
$ mkdir minecraft-data
$ docker run -it --name mc -v $PWD/minecraft-data:/data -p 25560:25565 -e EULA="true" itzg/minecraft-server
chmod: /data: Operation not permitted
usermod: no changes
Changing ownership of /data to 1000 ...
chown: /data: Operation not permitted
chown: /data: Operation not permitted
/start-configuration: line 10: eula.txt: Permission denied
/start-configuration: line 11: eula.txt: Permission denied
ERROR: unable to write eula to /data. Please make sure attached directory is writable by uid=1000
```

Namespace remapping is a security feature that maps a user id (UID) and group id (GID) inside a container, to another UID / GID on the host. Therefore, the root user inside the container is actually mapped to a non-privileged user on the host.

The problem for me was, that I created the data directory first using my normal user and then trying to use it as a volume for the minecraft container.

When the container starts, the start script tries to `chown` the data directory so that it belongs to the UID `1000` (inside the container). But because the root user inside is mapped to a non root user outside (in my case UID `296608`), this outside user is not allowd to do a `chown` of this directory.

The simple solution was to just delete the data directory and let docker create it.

```
$ rmdir minecraft-data
$ docker run .........
```

In case there is already data in the directory and you don't want to loose it, the solution is a *bit* more complicated:

1. Create a new temporary minecraft container with a new data directory and look what UID and GID it has (Press Ctrl+C to cancel the process after a few seconds)
    ```
    $ docker run --rm -it -v $PWD/minecraft-temp:/data -e EULA="true" itzg/minecraft-server
    usermod: no changes
    Changing ownership of /data to 1000 ...
    Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    2 1000     1000          4096 Sep 13 14:10 /data'
    [...]
    Starting the Minecraft server...
    ^C
    $ ls -ld /tmp/minecraft-temp/                                                                                                                                                                                                      
    drwxrwxr-x 5 297608 297608 4096 Sep 13 16:10 /tmp/minecraft-temp/
    ```
    Here the `297608 297608` part is the UID and GID.
    (The container is automatically removed after it has been stopped because of the `--rm` flag.)
2. Recursively change the UID and GID of the data directory manually:
    ```
    $ sudo chown -R 297608:297608 minecraft-docker/
    ```
    Notice that in the above line there is a colon "`:`" between the UID and the GID: `297608:297608`.
3. Delete the temporary directory:
    ```
    $ sudo rm -rf /tmp/minecraft-tmp
    ```

You could also calculate the UID and GID but that's already covered in the [documentation](https://docs.docker.com/engine/security/userns-remap/).

**Comment by itzg** [comment]
@Pristar4 can you provide new logs after pulling the latest `itzg/minecraft-server` image? The screenshot provided in the issue description is from an older version of the image, before some of the permission operations were updated...and described above wonderfully by @x3rAx .

**Comment by pilkch** [comment]
I had a similar problem that I solved by telling docker to mount the volume with selinux settings:
```bash
--volume /srv/minecraft:/data:Z
```
