### ISSUE TITLE
MC 1.20.5 does not start.

### ISSUE THREAD

**Issue by jovnas** [itzg/docker-minecraft-server#2798]
### Describe the problem

When trying to run Minecraft 1.20.5 I get the following error:
`java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0`

Adding `VERSION: "1.20.4"` to run the previous version works.

### Container definition

```
services:
  mc:
    image: itzg/minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25666:25565"
    environment:
      EULA: "TRUE"
      SERVER_NAME: "Helvete, Lars-Olof!"
      MOTD: "§l§dLars-Olof's\n§4Minecraft Server"
      ENABLE_COMMAND_BLOCK: "TRUE"
      WHITELIST: |
        XXX
      EXISTING_WHITELIST_FILE: "MERGE"
      OPS: |
        XXX
      EXISTING_OPS_FILE: "MERGE"
      ENABLE_ROLLING_LOGS: "TRUE"
      TX: "Europe/Stockholm"
      MEMORY: "2G"
      USE_AIKAR_FLAGS: "TRUE"
    volumes:
      - ./data:/data
```

### Container logs

```
+ exec mc-server-runner --stop-duration 60s java -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Xmx2G -Xms2G -Dlog4j.configurationFile=/data/log4j2.xml -jar minecraft_server.1.20.5.jar
Error: LinkageError occurred while loading main class net.minecraft.bundler.Main
        java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
2024-04-27T09:34:46.130Z        WARN    mc-server-runner        Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.        {"exitCode": 1}
2024-04-27T09:34:46.130Z        INFO    mc-server-runner        Done
```

**Comment by JayPi4c** [comment]
It seems like Minecraft 1.20.5 is compiled with java 21. You can see that in your logs as `[...] has been compiled by a more recent version of the Java Runtime (class file version 65.0)`. Since you probably reused an older container that still comes java 17 you need to update your container image to a newer version. This might be done by explicitly run `docker compose pull` to get the newest version of the latest tag.
I myself fixed the issue by pinning the version of the container to the latest release `2024.4.1` eg.
```yml
services:
  mc:
    image: itzg/minecraft-server:2024.4.1
...
```

When starting with this config, docker will be forced to pull the specific container which ships with java 21. This has the benefit of always knowing what version of the Minecraft docker container is used.

**Comment by jovnas** [comment]
Of course! Having `latest` in the compose file uses the locally cached version.  Why didn't I think of that? Oops! 😅
