### ISSUE TITLE
Question: Any downside to using your original mc-status?

### ISSUE THREAD

**Issue by ryantheleach** [itzg/docker-minecraft-server#323]
I notice that you have a reliance on python 2 due to mc-status, yet you had your own Java based solution previously.

Doesn't relying upon Dinnerbones MC-Status add potentially unnecessary dependencies?

Sorry I'm new to Docker, and have been learning via Minecraft servers (My default fallback to learning any new tech) but would appreciate any response.

Also slightly off topic for this ticket, but would/could you annotate the Docker files to better say the purpose of each of the lines? It would really serve as a great example to people like me.

Thanks!

**Comment by itzg** [comment]
It's funny you ask because just the other day I was noticing again that python was in the package list and then remembered that was for dinnerbone's mc-status. I'll have to look back at the git history to remind myself of why I switched away from my mc-status -- I'm guessing it was because it's a little bit awkward having multiple process trees in a single container.

For fun and compactness I have developed a few Go tools bundled into the container, so maybe I'll follow that pattern and write little tool that exercises Minecraft's ping messaging.

Yes, I'd be glad to add some comments in the Dockerfile. I've had a few people point out they're learning about Docker via this image.

**Comment by itzg** [comment]
I finally got a chance to address this in 9560903c800065e1925f18bee41b6680d6f2fa06 but actually used a new [mc-monitor](https://github.com/itzg/mc-monitor) tool I developed.

However, the removal of python was a premature since it then caused issues like https://github.com/itzg/docker-minecraft-server/issues/427 due to python still be used in other places.

**Comment by itzg** [comment]
I have pushed a new image, which (again) removes python but this time I found the two remaining uses of it and replaced them with non-python approaches.
