### ISSUE TITLE
Noob question about MODPACK, MODS and CF_SERVER_MOD.

### ISSUE THREAD

**Issue by Frenzoid** [itzg/docker-minecraft-server#359]
Hello!

so, about the environ. vars,
CF_SERVER_MOD is from where the server will download the server mod pack.
MODPACK is from where the server will download the client modpack
and MODS.. what is MODS for?

Sorry, i never used forge before.

**Comment by itzg** [comment]
Yeah, since the image supports several types of MC servers those variables do get confusing. All of them are server-side only, so the client aspect has be done separately from the container.

To differentiate the vars:
- `MODS` : for downloading individual mod/plugin jars. It puts them in `mods` for `TYPE=FORGE`, `plugins` for all others
- `MODPACK` : similar to `MODS` except it downloads a zip archive of mod/plugin jars
- `CF_SERVER_MOD` : similar to `MODPACK` that they are an archive with multiple Forge mods. [CurseForge modpacks](https://www.curseforge.com/minecraft/modpacks) come with the correct version of Forge server defined. [FeedTheBeast](https://www.feed-the-beast.com/) modpacks align with the Twitch launcher packs...which do configure the client for you.

Hope that all helps. (Note to self, I should document the above somewhere :) )

**Comment by Frenzoid** [comment]
Awesome, thanks for the aclaration!
