### ISSUE TITLE
Consider implementing alternative JVM

### ISSUE THREAD

**Issue by DJDANNY123** [itzg/docker-minecraft-server#360]
Alternative JVM's such as openJ9 ( https://www.eclipse.org/openj9/ or https://hub.docker.com/r/adoptopenjdk/openjdk8-openj9) can provide benefits such as higher performance/ lower memory usage ect. 
Have you considered using this as the base image, or making this an option?

**Comment by Enf0** [comment]
I second this. In the meantime, you can easily make the change yourself by cloning the repo and changing the first line in the Dockerfile from

`FROM openjdk:8u212-jre-alpine`
to
`FROM adoptopenjdk/openjdk9-openj9:alpine`
and running docker build.

**Comment by itzg** [comment]
_Sorry @DJDANNY123  and @Enf0 for the delay in responding -- this got lost in my notification list._

I have admit I haven't considered alternatives beyond the stock openjdk builds/images. I'm definitely willing to give this a try especially since I have a lot of faith the Eclipse foundation has created a good solution there.

Since the startup time of 1.14.x has gotten pretty horrible, it seems like running a few timings of each base image reaching world generated and ready state would be an easy case study.

I'll give that a try, but any contributions you can provide of measurement ideas and/or data would be fantastic.

**Comment by Enf0** [comment]
Here's a very interesting post about running Minecraft with OpenJ9:
https://steinborn.me/posts/tuning-minecraft-openj9/

**Comment by itzg** [comment]
Thanks. I'll add `-Xtune:virtualized` into the mix. So far, the startup time is not improved with j9, but memory usage is roughly cut in half.

**Comment by itzg** [comment]
Docker Hub is currently building the image based on OpenJ9. I have documented the two new opt-in tuning options in the JVM section of the README

https://github.com/itzg/docker-minecraft-server/#jvm-options

**Comment by itzg** [comment]
This is now available on Docker Hub.

**Comment by itzg** [comment]
There were reports in #374  of the container not starting, so I have reverted the openj9 base image change and moved instead to a branch and image tag of `openj9`.

**Comment by itzg** [comment]
@DJDANNY123 and @Enf0 , can you test out `itzg/minecraft-server:openj9` to see if it works ok for you also?

**Comment by Enf0** [comment]
Just pulled the openj9 build, seems to work just fine. Haven't had the chance to compare performance yet, but the server is running!

Here are my java flags, as per the article above:
`java -Xmns16384M -Xmnx26215M -Xgc:concurrentScavenge -Xgc:dnssExpectedTimeRatioMaximum=3 -Xgc:scvNoAdaptiveTenure -Xdisableexplicitgc -Xtune:virtualized -Xms32G -Xmx32G -jar paper_server.jar --noconsole`

**Comment by DJDANNY123** [comment]
I'm only running docker on my raspberry pi 4 (4GB) so would need a multiarch-openj9 build/image to test it as without multiarch I get:
`standard_init_linux.go:211: exec user process caused "exec format error"
`
Which I believe is expected.
If I have time I might try to build the image myself but am reasonably new to linux and am running a headless setup (just ssh-ing into)

**Comment by itzg** [comment]
Ooh, I’ll have to give it a try on my rpi3. I had given up on running the Minecraft server there due to its sluggish performance, but maybe j9 resolves that.

**Comment by DJDANNY123** [comment]
> 
> 
> Ooh, I’ll have to give it a try on my rpi3. I had given up on running the Minecraft server there due to its sluggish performance, but maybe j9 resolves that.

If you could publish an openj9-multiarch image/rpi architecture to dockerhub while you do this that would be great!

I have managed to run a curseforge server with pretty good performance on my rpi4 4GB before openj9 so wanting to see if I can observe much of a difference.

**Comment by DJDANNY123** [comment]
According to [https://github.com/eclipse/openj9/issues/53](url), it looks like support for the raspberry pi architecture (armv71) is not available while using openj9, found when trying to build the dockerfile on my rpi4.
Some alternatives may be something like GraalVM, however I have not researched this.

**Comment by itzg** [comment]
[This comment](https://github.com/eclipse/openj9/issues/53#issuecomment-330310397) makes it sound like Java 8 might be supported, which is the variant I ended up using to avoid any surprises with mods/plugins. Last night I discovered the `--platform` option of `docker build`, so I started to make progress on cross-platform building of the image.

**Comment by quorn23** [comment]
> Just pulled the openj9 build, seems to work just fine. Haven't had the chance to compare performance yet, but the server is running!
> 
> Here are my java flags, as per the article above:
> `java -Xmns16384M -Xmnx26215M -Xgc:concurrentScavenge -Xgc:dnssExpectedTimeRatioMaximum=3 -Xgc:scvNoAdaptiveTenure -Xdisableexplicitgc -Xtune:virtualized -Xms32G -Xmx32G -jar paper_server.jar --noconsole`

Would you mind share how you add those properly to the docker image? Might be caused by my headache, but i seem to fail to start the container with the proper parameters.

**Comment by itzg** [comment]
@quorn23 I'm guessing @Enf0 used the `JVM_XX_OPTS` described [in this section](https://github.com/itzg/docker-minecraft-server#jvm-options), such as:

```
-e JVM_XX_OPTS="-Xmns16384M -Xmnx26215M -Xgc:concurrentScavenge -Xgc:dnssExpectedTimeRatioMaximum=3 -Xgc:scvNoAdaptiveTenure -Xdisableexplicitgc -Xtune:virtualized" -e MEMORY=32G
```

**Comment by DJDANNY123** [comment]
Might try the Zulu JVM base image some time soon on my RPi4, which emphasises it's ARM support:

https://hub.docker.com/r/azul/zulu-openjdk-alpine

https://technology.amis.nl/2018/11/23/comparing-jvm-performance-zulu-openjdk-openjdk-oracle-jdk-graalvm-ce/#prettyPhoto

**Comment by itzg** [comment]
The Zulu base image does look promising.

**Comment by wlp7s0** [comment]
Hello @itzg ,
Just pulled master and changed image name in Dockerfile to 
`adoptopenjdk/openjdk8-openj9:alpine-nightly`
Image is building and starting with no issue. Also tried to use
`adoptopenjdk/openjdk8-openj9:alpine` 
stable version - both work. But both have a strange behaviour. Running FORGE 1.12.2 + RLCraft pack server stops on "Applying holder lookups". Managed to do some experiments, found a solution - disable or enable any mod in a pack. Strange, but after this is done - server start.  

I've checked [#374 ](https://github.com/itzg/docker-minecraft-server/issues/374) and I think that there was no issue with your build whatsoever. The problem is that after you've changed your build's image - docker used image that it pulled, but it had some data already cache for this build. It does not recreate it. That's why @Klemen1337 had new image of your docker but old (cached) data it starts with. And that's why removing docker image (removes cache) and starting it again helped. 

Also, I need an advice. I was so exited when I found this thread and I rushed to test openJ9 with RLCraft mod pack. But after quite few tests I'm disappointed because the performance of the server actually decreased. I need to perform some additional tests though. 
I'm using [options](https://steinborn.me/posts/tuning-minecraft-openj9/) from this example. May be there are some additional\different options I can try with mc server?

Thank you! This docker image is awesome!

**Comment by itzg** [comment]
Thank you @wlp7s0 for such a thorough examination of the j9 base image and the root cause of #374 . 

Hearing your final outcome though confirms I am making the right decision with keeping the mainline/latest tag on the standard openjdk image (I am traditionally bit of a Java purist in my development career). 

With that said, I'll work on creating a process (automated or manual) to maintain an alternative image tag where the `adoptopenjdk/openjdk8-openj9:alpine` base image is used.

**Comment by itzg** [comment]
@wlp7s0 yep, I'm thinking exactly the same thing, so that's great.

**Comment by mstoodle** [comment]
If start-up performance is an issue, have you tried adding `-Xshareclasses` to the OpenJDK with Eclipse OpenJ9 command line? Adding this option allows the JVM to automatically store both classes and compiled code which can dramatically (30%-50% in many cases) improve start-up performance.

You may then want to re-evaluate the use of `-Xtune:virtualized` in conjunction with `-Xshareclasses` to measure the impact to both start-up and performance as the aggressive use of cached compiled code when both those options are used can, for some applications, reduce performance by a few percent (which presumably you don't want).

If you only use `-Xshareclasses` without `-Xtune:virtualized` then cached compiled code will only be used during start-up which tends to have a very low impact to overall performance.

**Comment by itzg** [comment]
That reminds me, I forgot to follow-up on this issue that I now provide additional image tags at https://hub.docker.com/r/itzg/minecraft-server/tags:
- openj9 (JDK 8 but OpenJ9 JVM)
- openj9-nightly (same, but their nightly image build)
- adopt11 (JDK11 provided by AdoptOpenJDK)

**Comment by C0Nd3Mnd** [comment]
Are you planning to expand the openj9 builds to more recent versions (11, 14, 15 etc.)? The images are available (for Java 11 for example: https://hub.docker.com/r/adoptopenjdk/openjdk11-openj9).

**Comment by itzg** [comment]
@C0Nd3Mnd I could...but it becomes overwhelming to support all the permutations of JVM provider, Java version, and base OS version. I'd be open to adding one combination of those, like the Java 11 openj9 example you provided. Would that one be sufficient?

I just realized I should probably close out this issue, but I'll spin off the openj9 + java version item to a new issue.
