### ISSUE TITLE
K8s Examples

### ISSUE THREAD

**Issue by sfxworks** [itzg/docker-minecraft-server#362]
I have some partially templated charts based around your deployment if you would like

https://github.com/mcserverhosting-net/charts/blob/master/server-deployment/templates/server-deployment.yaml

I plan to expand upon them in the next few days. Open to some PRs for helm based deployments?

**Comment by itzg** [comment]
I think it would be great to have a "Deployment Examples" (or something like that) section in the README that would list sources like yours along with the server-only Helm chart https://github.com/helm/charts/tree/master/stable/minecraft . Selfishly, I can also throw in my not-so-elegant kubernetes deployment file I copy-tweak-paste :)

In summary, it's fantastic to see your work there and I'd really like to showcase it. Feel free to submit a PR against the README for that new section or let me know when you're ready to be linked and I'll create the section.

Since I'm hijacking your issue to make notes about things to list in that section, I should also mention that this Kubernetes operator would be great thing to include: https://github.com/fabianvf/game-server-operator

**Comment by sfxworks** [comment]
MMm
The operator actually mocs something I had cooking in private. I am circumventing ansible to avoid another layer of abstraction, but that is a very interesting find. Either way, doing some clean up myself of the chart and after that count me in on that PR!

**Comment by itzg** [comment]
Resolved by adding a deployments section to the README in https://github.com/itzg/docker-minecraft-server/pull/461
