### ISSUE TITLE
Feature Request - Tagging releases on hub.docker.com

### ISSUE THREAD

**Issue by LandonStewart** [itzg/docker-minecraft-server#375]
Perhaps having an entirely different image name for each architecture would be better than having one image with different tags for architectures.  The result would be the ability to use the tags for version numbers.

Like this:
- its/minecraft-server (for x86)
- itzg/minecraft-server-rpi3:latest
- etc

Then within those a tag for the version number with latest being the most recent version.  You could then split your different architectures out on GitHub as well each with versioning and releases there.

**Comment by itzg** [comment]
I like that idea. I think I would need to move away from doing the build on Docker Hub to pull that off. That’s quite doable since I do some other app image builds directly on CircleCI. 

The manifest associated with the “multiarch” tag actually auto adapts to the host platform. I need to improve the automation of updating that tag.
