### ISSUE TITLE
FTB/Curse Server: chmod: /data: Permission denied

### ISSUE THREAD

**Issue by NicolasLoisier** [itzg/docker-minecraft-server#390]
I can't launch my minecraft server with the modpack ftb stoneblock 2. I have the latest docker image. I use the following command to run the container:

>docker run -d  \\
>-v /app/MinecraftServer/FTBPresentStoneblock2Server_1.15.0/data:/data \\
>-e TYPE=CURSEFORGE -e CF_SERVER_MOD=StoneBlock-1.0.35-Server.zip \\
>-p 25565:25565 -e EULA=TRUE --restart=always \\
>--name mc itzg/minecraft-server

And the error was:

>chmod: /data: Permission denied
>usermod: no changes
>Changing ownership of /data to 1000 ...
>chown: /data: Permission denied
>/start-configuration: line 20: eula.txt: Permission denied
>/start-configuration: line 21: eula.txt: Permission denied
>ERROR: unable to write eula to /data. Please make sure attached directory is writable by uid=1000

Do you have an idea of ​​what I'm doing wrong?

**Comment by akBeater** [comment]
Hi,
i had a similar problem with my curseforge RLCraft Server.
I followed this post from itzg: https://github.com/itzg/docker-minecraft-server/issues/193#issuecomment-362829296.
I think the problem is, that the docker has no permissions to the files you store in: /app/MinecraftServer/FTBPresentStoneblock2Server_1.15.0/data
In my case, I could create a running server, but when I added mods, the logs showed **no permissions** after every mod-loading.
What i copied below fixed my problem - so i hope your issue, too.

You can try this:
root> useradd -u 5000 -U -m user5000
root> usermod -a -G docker user5000
root> sudo -i -u user5000

user5000> docker run -d -e EULA=TRUE \
  -v /home/user5000/data:/data -e UID=5000 -e GID=5000 \
  -e TYPE=CURSEFORGE -e CF_SERVER_MOD=StoneBlock-1.0.35-Server.zip  \
  -p 25566:25565 \
  --name mc \
  itzg/minecraft-server

Run the docker **only** as user5000.

~akBeater

**Comment by NicolasLoisier** [comment]
@akBeater thanks for the answer but I have the same issue:

>chmod: /data: Permission denied
>Changing ownership of /data to 5000 ...
>chown: /data: Permission denied
>/start-configuration: line 20: eula.txt: Permission denied
>/start-configuration: line 21: eula.txt: Permission denied
>ERROR: unable to write eula to /data. Please make sure attached directory is writable by uid=5000

**Comment by itzg** [comment]
@NicolasLoisier can you check on a couple of things? First, please make sure you have pulled the latest image. With that, one of the first few lines of output will be a "Running as" line, such as the following. Can you provide that line?

```
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Sep 26 01:26 /data'
```

Also, are you making use of user remapping in your Docker setup?
https://docs.docker.com/engine/security/userns-remap/

**Comment by NicolasLoisier** [comment]
@itzg Yes, I have the latest image.
I don't have/find the line  "Running as"
I don't used remapping but I try and nothing change

**Comment by itzg** [comment]
@NicolasLoisier , can you provide the output of `docker pull itzg/minecraft-server` so I can double check what is being pulled vs published?

**Comment by NicolasLoisier** [comment]
log from docker pull:

Using default tag: latest
Trying to pull repository docker.io/itzg/minecraft-server ...
latest: Pulling from docker.io/itzg/minecraft-server
e7c96db7181b: Already exists
f910a506b6cb: Already exists
b6abafe80f63: Already exists
2f6fd934326c: Already exists
7bd2aba5fbaf: Already exists
712fb72fbd24: Already exists
bd6d52f30aa2: Already exists
d215879dce27: Already exists
ec1fea4c576f: Already exists
fd7e3b6ddeb2: Already exists
7f75b6d0d267: Already exists
66b2fdfb6608: Already exists
f3031a66c40f: Already exists
0954474b28a2: Already exists
edc99c83c3bf: Already exists
6fda5687dde0: Pull complete
ff3b3ad6a2b0: Pull complete
Digest: sha256:5e37c6d3e89c82dff211664ef4ead489b5f1bbe8e6965e6c89ecd90748734fbb
Status: Downloaded newer image for docker.io/itzg/minecraft-server:latest

**Comment by itzg** [comment]
@NicolasLoisier thanks. Yes, that is indeed the correct image I was expecting. External to Docker are you able to change the ownership of the attached data directory to uid=5000? From the log statements, that should theoretically fix it.

**Comment by pilkch** [comment]
I had a similar problem that I solved by telling docker to mount the volume with selinux settings:
```bash
--volume /srv/minecraft:/data:Z
```

**Comment by benni-tec** [comment]
Just experienced the same issue while migrating from ubuntu server to centos due to infrastructure. Also I'm using podman now since it is the native implementation. I thought this was causing the problem

> I had a similar problem that I solved by telling docker to mount the volume with selinux settings:
> 
> ```shell
> --volume /srv/minecraft:/data:Z
> ```

Tried this solution and it worked! Seems the problem is related to the filesystem of SELinux. maybe you could mention this in the documentation @itzg ? I know it is not a problem with your container but rather of OCI Containers still it might help newcomers!

Have a great weekend! Benni

**Comment by derelbenkoenig** [comment]
I have the same issue with the Forge server on a Centos machine in digital ocean. I tried manually `chown`ing the directories to user 5000 after creating a user 5000 on the host machine, and no luck

**Comment by derelbenkoenig** [comment]
Ah, so apparently the cause (or _a_ possible cause, in at least my case) is SELinux related. https://prefetch.net/blog/2017/09/30/using-docker-volumes-on-selinux-enabled-servers/
adding a `:Z` to the end of the `-v` arg to `docker run` seems to have resolved it

**Comment by rhofour** [comment]
I just ran into the same thing. It might be nice to include an update to the docs warning about this.
