### ISSUE TITLE
How can i execute a command without rcon-li?

### ISSUE THREAD

**Issue by FoxGamingMC** [itzg/docker-minecraft-server#395]
I want that I can execute a command with docker exec but that the output is in the logs.
With rcon-li, the output of a command does not end up in the logs.
How do you do that?

**Comment by itzg** [comment]
If you make sure to start the container with stdin and tty enabled, `-it` for `docker run` or the following for a [compose declaration](https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir):

```yaml
stdin_open: true
tty: true
```

then issuing commands via [docker attach](https://docs.docker.com/engine/reference/commandline/attach/) is showing up in logs when I try it. You'll use Ctrl-p and Ctrl-q to detach without stopping the container.

**Comment by FoxGamingMC** [comment]
I want that my panel can execute it in one line automatically.

**Comment by itzg** [comment]
I am afraid I can't find a solution for your scenario. I double checked that `rcon-cli` usage only directs output over the rcon connection. Even using `echo "help" | docker attach mc` didn't work as a one-shot command usage -- it just states `the input device is not a TTY`.

**Comment by denzuko** [comment]
> I want that I can execute a command with docker exec but that the output is in the logs.

Not going to happen. the stdin, stderr, and stdout of PID 1 or its non-forked children are the ones that docker are monitoring. So `docker exec` is creating an entirely different branch of the process tree thus its stdin, stderr, and stdout would not be picked up by PID 1.

Might want to try `echo "help" | docker attach -i mc`; where *-i* attaches as an interactive session. But this may have issues as well given stdin/stdout is going to be out of sync since the docker command doesn't hold stdin open the same way most unix commands (e.g less/more/dd etc.) do.

**Comment by itzg** [comment]
Good suggestion @denzuko , but `docker attach` doesn't have a `-i` or equivalent option :( 

```
Usage:	docker attach [OPTIONS] CONTAINER

Attach local standard input, output, and error streams to a running container

Options:
      --detach-keys string   Override the key sequence for detaching a container
      --no-stdin             Do not attach STDIN
      --sig-proxy            Proxy all received signals to the process (default true)
```
