### ISSUE TITLE
Could i use the "docker commit" to save the running status?

### ISSUE THREAD

**Issue by IwasawaMasami** [itzg/docker-minecraft-server#401]
Sorry, i'm newer for docker. So i don't know the idea that can be right if i want to save the installed-server[healthy status] as a new image to be convenient for running in everywhere.

**Comment by itzg** [comment]
I would have to research the exact behavior since the `/data` path within the container is a volume and I don't believe `docker commit` includes volume paths.

The easiest solution that I know definitely works is to volume attach the data directory from a directory on your host, such as:

```
docker run -it --name mc -e EULA=TRUE -v /path/on/host:/data itzg/minecraft-server
```

You can either stop the container and make a copy of the host directory (`/path/on/host` in my example) 

...or you can tell the minecraft server to pause and flush any world changes using:

```
docker exec mc rcon-cli save-off
docker exec mc rcon-cli save-all
```

make a copy of the host directory and then re-enable saving

```
docker exec mc rcon-cli save-on
```

**Comment by IwasawaMasami** [comment]
Thanks a lot, i think i have got this! :)

**Comment by itzg** [comment]
I was just wondering why the issue is re-opened? Did you need further advice about the original issue or just a mis-click?

**Comment by IwasawaMasami** [comment]
Sry ,May it's because of the network issues. i don't know why it open again.
