### ISSUE TITLE
RAM Usage not updating

### ISSUE THREAD

**Issue by madfknmax** [itzg/docker-minecraft-server#410]
Hi and first of all: thanks for your awesome container! 
I'm currently having difficulties updating my container to use 12G of RAM and not 1G as its default setting is.
I have tried adjusing the config.v2.json file by changing the MEMORY=1G to 12G but it didnt work.
Even tried docker update... nothing.

Any help maybe?

Thanks in advance!

this is what parameters i pulled the container with:

docker run -d -v /home/max/rlcraft:/ -e VERSION=1.12.2 -e TYPE=FORGE -e FORGEVERSION=14.23.5.2838 -e  -p 25565:25565 -e EULA=TRUE --name rlcraft itzg/minecraft-server ( I am hosting a RLCRAFT server)

**Comment by itzg** [comment]
Just to confirm, you tried passing `-e MEMORY=12G` on the command line and that didn't work? (I don't see it in the snippet you provided, but maybe had tried previously.)

To sanity check, I set the following to 2G (since my laptop doesn't have 12G available) 

```
docker run -d -e EULA=TRUE -e TYPE=FORGE -e VERSION=1.12.2 -e FORGEVERSION=14.23.5.2838 -e MEMORY=2G --name rlcraft itzg/minecraft-server
```

and confirmed in the log that I saw:
```
Setting initial memory to 2G and max to 2G
Starting the Minecraft server...
```

and `exec`ing into the container ps shows the correct `-X` command line args:
```
$ docker exec rlcraft ps -f
PID   USER     TIME  COMMAND
    1 minecraf  0:00 mc-server-runner --stop-duration 60s java -XX:+UseG1GC -Xms2G -Xmx2G -jar forge-1.12.2-14.23.5.2838-universal.jar
   74 minecraf  1:07 java -XX:+UseG1GC -Xms2G -Xmx2G -jar forge-1.12.2-14.23.5.2838-universal.jar
```

BTW, for the volume mount (`-v`), it's expected to mount that at `/data` within the container since that's the working directory; however, perhaps that was just a typo in your snippet.

**Comment by madfknmax** [comment]
Thanks for the quick response! Yes that was a typo.
No i run the Container without any MEMORY param.
I Start and Stop the Container with docker start/stop rlcraft.
Can i run the Container and only add the MEMORY=12G and it just Updates this Parameter?
Like docker run ... -e MEMORY=12G...?

**Comment by itzg** [comment]
Since you're attaching the `/data` volume the remainder of the container itself is stateless, so yes you can simply recreate the container with another `docker run` including the `-e MEMORY=12G` argument.

**Comment by madfknmax** [comment]
Thanks for your quick response!
once again: great container. keep it up :)
