### ISSUE TITLE
Upgrade documentation

### ISSUE THREAD

**Issue by hyperbolic2346** [itzg/docker-minecraft-server#418]
Looking for upgrade instructions for a minecraft server run on this image. It says that the container downloads the latest image, but I assume that if it sees an existing install it will not download even if the default stable version is higher. Is this due to minecraft not supporting upgrades or is there an upgrade path available to tell the install script to download the latest version again? Did I miss it in the readme?

**Comment by itzg** [comment]
That's a good point that the README doesn't explicitly state how to perform an upgrade. I'll write a specific section for that. Until then...

If `VERSION` is set to "LATEST" (the default) then it will identify the latest stable version and if a minecraft server jar is not present for that version specifically, it will download and use the new version. That logic works since the filename contains the version, such as `minecraft_server.1.15.1.jar`.
