### ISSUE TITLE
Can't run the image on Raspberry Pi

### ISSUE THREAD

**Issue by BartoszMiz** [itzg/docker-minecraft-server#420]
When I try to run the image on my Raspberry Pi 4 with Raspian Lite I get:
> standard_init_linux.go:211: exec user process caused "exec format error"

I used this command to start it:
> docker run -p 25565:25565 --name mc itzg/minecraft-server

It's the first one shown on the Docker Hub page just without the "detached" flag. I also tried to run it with this docker-compose:
`
version: "3"
services:
    minecraft-server:
            image: itzg/minecraft-server
        container_name: minecraft-server
        ports:
            - "25565:2556" 
              environment:
              EULA: "TRUE"
              TYPE: "SPIGOT"
              VERSION: "1.15.1"
        volumes:
                - /home/pi/docker_apps/minecraft_data:/data
        tty: true
        stdin_open: true
        restart: always
`
Same error is shown but a few times. I don't know whether it's an issue with the container (most likely it's not) or I'm just stupid and it's obvious that the image won't work. It's literally my first time using Docker. I'm lost. Please help.

**Comment by itzg** [comment]
@BartoszMiz I need to fix the multi-architecture build pushed there since the ARM variant is not properly ARM.

Unfortunately there's also lots of issues we're all finding running the Minecraft server on Raspberry Pi 4 (and others):

https://github.com/itzg/docker-minecraft-server/issues/316

I'll close this issue and we can consolidate discussion on that one.
