### ISSUE TITLE
minecraft-server imageTag rpi3 ran into issues with rcon-cli

### ISSUE THREAD

**Issue by orsenthil** [itzg/docker-minecraft-server#433]
```
helm install stable/minecraft --version 1.1.6 --set=imageTag=rpi3 --set minecraftServer.eula=true --generate-name
```

I saw the following problem in the logs.

```
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    6 0        0             4096 Feb  2 17:41 /data'
Checking version information.
Checking type information.
server.properties already created, skipping
Checking for JSON files.
Copying any mods over...
Setting initial memory to 512M and max to 512M
Starting the Minecraft server...
2020/02/02 17:42:55 Stopping with rcon-cli
2020/02/02 17:42:55 ERROR Failed to stop using rcon-cli exit status 1
2020/02/02 17:42:55 Sending 'stop' to Minecraft server...
2020/02/02 17:42:55 Waiting for completion...
```

**Comment by itzg** [comment]
I tried 1.15.2 yesterday on my RaspberryPi 3 and it failed miserably. I had to power-cycle the entire RaspberryPi to even ssh back to it. The logs you reported don't indicate an rcon-cli problem; instead the problem is that the minecraft server itself is not ready or responsive enough to even respond to rcon connections/operations.

I thought I would try an older version, 1.12.2, and even that maxes out one of the cores without making any visible progress:

![image](https://user-images.githubusercontent.com/988985/73619475-2c404380-45f3-11ea-8d4f-5c57999b275d.png)

Finally, I tried 1.7.10 and it starts up slowly but is actually making progress through the "Preparing spawn area" steps.
