### ISSUE TITLE
'Multiarch' memory allocation is too large for Raspberry Pi 3

### ISSUE THREAD

**Issue by MarcDoughty** [itzg/docker-minecraft-server#443]
Would it be possible to drop the Java memory allocation in the Multiarch target from 1GB to 700MB, or let it dynamically allocate? The 1GB footprint is too high to run on the Raspberry Pi 3B+ under AMD64 Ubuntu.

**Comment by itzg** [comment]
Hmm, I can't think of an easy way to have the env var vary by platform built by BuildKit. The memory allocation can be overridden by passing `-e MEMORY=700M`. Would that be good enough?

**Comment by MarcDoughty** [comment]
I'm playing with this idea over here https://github.com/MarcDoughty/docker-minecraft-server. I flipped it over to Ubuntu-based images for familiarity reasons.

I just built, ran, and played against it a bit on my desktop with nothing horrible happening. I'll see how it runs on the Pi 3B+ with two players soon.

I'm very new to git, and Docker. I hope you don't mind my fork!

I also filed a feature request with the Ubuntu people to see if they can enable Transparent HugePages on the raspi2 kernels so we can run this in 350 2MB pages instead of 175,000 4KB entries in the page table. Might speed things up, might turn it into an unstable mess.

**Comment by itzg** [comment]
Forking is very welcome, so experiment away.

I do want to point out that the `multiarch` branch was already switched over to Debian since armv7 and aarach64 were not readily available on Alpine. I'm a major user of Ubuntu and found the Debian base image is familiar enough.

So...I'd recommend you start from `multiarch` branch rather than `master` for the experiments you're doing. Just note that you'll need to either set the three build args listed here

https://github.com/itzg/docker-minecraft-server/blob/multiarch/Dockerfile#L32-L36

with `--build-arg` on a regular `docker build` or use `docker buildx` with BuildKit where it'll set those platform arguments automatically. I use the latter to do the multiarch image build that is currently pushed to Hub.

**Comment by itzg** [comment]
I have added a section to README that discusses the new tag for rpi and notes the memory config should be adjusted:

https://github.com/itzg/docker-minecraft-server#running-on-raspberrypi

**Comment by MarcDoughty** [comment]
I cloned the 'multiarch' branch locally and changed the Dockerfile to source from adoptopenjdk:latest, which is based on Ubuntu Focal with JDK 15.

With very few changes, it works beautifully. I also made a set of flags (much like the Aikar flags) that optimize for performance in a restricted environment (e.g. use Shenandoah GC, only run one GC thread, and only trigger it when the JVM's memory is almost full). There are some tweaks for Transparent Huge Pages as well.

I would be happy to split these up and try checking them into a new branch, maybe something like 'multiarch-adopt-latest' or something.

I can see some advantages to being primarily on 'multiarch', with a branch that is based on the latest Forge-compatible AdoptOpenJDK and another that tracks the current JDK release, especially with AWS starting to offer ARM64-based EC2 instances at a lower cost than amd64. It would also get the Helm charts and docker-compose orchestrations onto a cross-platform track.

**Comment by itzg** [comment]
@MarcDoughty a few PRs for each of the ideas makes sense to me. How about simply "multiarch-latest" for the branch name? If that works for you, I'll create the branch and let you target the PRs at that.

**Comment by MarcDoughty** [comment]
That sounds great! Thanks!

**Comment by itzg** [comment]
@MarcDoughty the branch has been created https://github.com/itzg/docker-minecraft-server/tree/multiarch-latest . It's currently a branch off of `multiarch`.
