### ISSUE TITLE
I got an error in forge mode 1.15.2

### ISSUE THREAD

**Issue by fillanes** [itzg/docker-minecraft-server#447]
Hi, first of all thank you for your work. The container in vanilla works like a charm. But i have problem with the forge mode. I got this error message from the container after i log in "[**00:50:29] [Netty Epoll Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.ModIdArgument@180f5798 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!**" and then the server kick me and put this message in the client "**Internal exception: java.io.IOException: An existing connection was forcibly closed by the remote host**". 

For the comand to execute the container was:
docker run -d -it -e VERSION=1.15.2 -e TYPE=FORGE -e FORGEVERSION=31.1.18 -e EULA=TRUE -p 25565:25565 -v /home/bender/conf-server/data:/data --name mc-forge itzg/minecraft-server

i searched the forge version here https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.15.2.html 

If you can guide me, helps a lot. And thanks again for the container. Most of the time i used in vanilla mode. Thanks

**Comment by wlp7s0** [comment]
Hello @fillanes 
It looks like you have a problem with forge module. Try to remove modules one by one until you will be able to connect.

**Comment by itzg** [comment]
@fillanes I finally got a chance to give this a try and I see one of the errors similar to yours, but I am still able to connect and play fine without any mods installed (see logs below and I used `list` to confirm the server reported my player connected.) I agree with @wlp7s0 that you will need to add your mods one by one to confirm which one causes the issue.

```
[20:19:29] [Server thread/INFO] [minecraft/DedicatedServer]: itzg joined the game
[20:19:29] [Netty Epoll Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.ModIdArgument@27bd985d (class net.minecraftforge.server
.command.ModIdArgument) - will not be sent to client!
[20:19:29] [Netty Epoll Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@23077f56 (class net.minecraftforge.server.
command.EnumArgument) - will not be sent to client!
[20:19:32] [Server thread/ERROR] [ne.mi.fm.ne.si.IndexedMessageCodec/SIMPLENET]: Received empty payload on channel fml:handshake
[20:19:32] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 3356ms or 67 ticks behind
[20:19:54] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 7217ms or 144 ticks behind
list
[20:20:15] [Server thread/INFO] [minecraft/DedicatedServer]: There are 1 of a max 20 players online: itzg
```

**Comment by fillanes** [comment]
First of all thanks for the reply to boths. Second, i want to try this weekend a second chance to this, and check again. I don't now much about the composition of a minecraft server, actually im learning here with my knowledge with docker. And a explained my steps.

1. I docker run the container, and use docker cp to extract /data folder.
2. i docker run another container and share the volume extracted with the new container and i buckup the folder data for new containers. And run a vanilla server with default values.
3. I run a forge server with that extrated folder (used for vanilla servers) and test the forge container and get that error that kickme. Posible my mistake was, use that data folder, and not to copy or extract with docker cp a forge container data folder .
4. Get the errors and post here
5. Next step is check again, and run a docker container without shared volume, and use docker cp for extract the data folder.

I didn't test any mod, and recieve that error and kick me the server. So please wait, and i give you more information about the next one test.

I used an ubuntu droplet witj 18.04 version, if you ask for the sistem. And the last thing, maybe ai made some mistake writing this, and the reason is i don't know very well english, i speak spanish . Any way thanks for the help, i'm gona test and share my experience with you

**Comment by itzg** [comment]
All good information. First of all, I don’t think it’ll work to share world data from a vanilla server to forge. I’m hopeful that your test with item 5 will work much better. BTW, I didn’t bother including the `FORGE_VERSION` when I tested since the startup script will locate the recommended version anyway.

**Comment by wlp7s0** [comment]
I'm trying to figure out what might go wrong. But it looks like a lot. May I ask you -
1. Why do you use `docker cp` for extracting world's data? For this to be perfectly secure - you need to stop a minecraft server itself to prevent files change and to close all currently open files. But if you do this - it will stop container, unless you change the entry point. My question is: why not to mount the volume as it is described [here](https://github.com/itzg/docker-minecraft-server#attaching-data-directory-to-host-filesystem)? 
2. @itzg is correct. It is not a good idea to share the data between vanila and forge. But I don't think it will actually disconnect a client because of this. At least, after spending some time googling the error, I concluded that the error is related to some module. 

Try next:
1. Use a completely blank data directory to start forge
2. Make sure you have the same forge version on the server and the client and client has no modules installed
 - This will be a blank forge test. It should work and you should be able to connect to the server. 
3. Now - copy modules you want to use on the server and on the client (I assume that most of the forge modules that you are using should be installed on both sides). Restart the server.
 - now you may receive the connection error. If so - 
4. remove half of the modules on the server and the client (same ones) and check again. If you will be able to connect - the problematic module is in the half that you removed. If not - remove another half. So on..

By doing this you will be sure that forge without modules works correctly. That the problem is in modules and 4th step will help you to pinpoint you to the module that causes the problem
