### ISSUE TITLE
Low RAM Usage but High Swap Usage

### ISSUE THREAD

**Issue by Radicitus** [itzg/docker-minecraft-server#489]
Hey!

The server works great, but I've been having issues with using less than the allocated RAM, 8G in my case, at around 2-3GB but high Swap usage. Sometimes the usage goes up to the full 4GB Swap and I need to restart the server. Any suggestions?

I don't know if this is relevant, but I'm on release 20200326 for stability. Thanks!

**Comment by itzg** [comment]
It sounds like there’s more going on with your system beyond the Minecraft container, so I’m not sure what advise I can can give. The only thing I can suggest generically for Linux systems is that swap can probably be turned off for most server hardware or at least turn the swappiness parameter down. 4GB of swap means your system overall is in a really place since disk I/O or horribly slower than RAM throughout.

**Comment by ElizabethMorves** [comment]
do not copy large files inside the system or clear memory after copying.
```
#!/bin/bash

case "$1" in

cache)
sync; echo 1 > /proc/sys/vm/drop_caches
;;

swap)
sync; echo 1 > /proc/sys/vm/drop_caches
swapoff -a && swapon -a &
;;

*)
echo $"Usage: $0 { cache | swap }"
esac

```

**Comment by yllekz** [comment]
Not sure if this is still an issue for you, but there are a couple of threads on Mojang's bug tracker regarding performance issues with a few of the recent Minecraft Server versions (other issues are linked in the comments): https://bugs.mojang.com/browse/MC-191659
