### ISSUE TITLE
Image has problems scaling up with docker swarm

### ISSUE THREAD

**Issue by ImuustMINE** [itzg/docker-minecraft-server#516]
I successfully started my first instance of docker-minecraft-server on my docker swarm worker node. However rescaling the replicas from 1 to 10
`docker service scale mc_test=10`
didn't do the trick only 1 instance is available even after hours of waiting.

Some things I noticed:
 - The status of all instances switches between the running and starting progress or are unhealthy:
```
1/10: running   [==================================================>] 
2/10: starting  [============================================>      ] 
3/10: task: non-zero exit (137): dockerexec: unhealthy container 
4/10: starting  [============================================>      ] 
5/10: starting  [============================================>      ] 
6/10: task: non-zero exit (137): dockerexec: unhealthy container 
7/10: running   [==================================================>] 
8/10: running   [==================================================>] 
9/10: starting  [============================================>      ] 
10/10: starting  [============================================>      ] 
```
 - The CPU usage is at 96%
 - Following error appears in the log of every instance that isn't available:
```
 [20:15:09] [Server thread/INFO]: Found new data pack vanilla, loading it automatically
 [20:15:09] [Server thread/INFO]: Reloading ResourceManager: Default
 [20:15:28] [Server thread/INFO]: Loaded 6 recipes
 2020/04/30 20:15:42 Stopping with rcon-cli
 2020-04-30T20:15:42.736Z      ERROR   mc-server-runner        ERROR Failed to stop using rcon-cli  {"error": "exit status 1"}
 2020-04-30T20:15:42.737Z      INFO    mc-server-runner        Sending 'stop' to Minecraft server...
 2020-04-30T20:15:42.737Z      INFO    mc-server-runner        Waiting for completion...
```
The current laborious workaround is scaling it up slowly:
 `docker service scale mc_test=5`
wait some minutes
`docker service scale mc_test=10`

I'm not sure if this issue is related to the docker-minecraft-server image or can be fixed by modifying  the image. But I think it is at least worth mentioning it.

(This issue isn't related to https://github.com/itzg/docker-minecraft-server/issues/514 I already checked 😉)

**Comment by wlp7s0** [comment]
I might be wrong, but I don't think you can use scale with this image at all. 
While creating new instances will create a different servers to work with the same world, it is not possible to determine what instance's service should have a priority upon world's change. Besides, as Minecraft server opens an external port to forward to the container, each replicated instance will be assigned a new random external port to listen to. For example: only one container will have '25565:25565' port forwarded and all the other will be assigned a random one '16788:25565'. 

About world's problem - as all containers will share the same world (because they will share the same /data directory and configuration), only one will be able to work with the world. And I believe that Minecraft server uses some locks on world's file to make sure that the file is accessed only by one Minecraft server at the time. 

Also, I don't understand why do you want to use scale? In the example above, you will have 10 instancies with 1GB RAM limit, using 10 GB of RAM total, but because only one of them is really working, your Minecraft server will be using maximum 1GB of RAM and all the rest 9BG will be the overhead that will never be used. You can't use it in this scenario.

**Comment by itzg** [comment]
@ImuustMINE, I agree with @wlp7s0, the Minecraft server itself (nothing to do with the container) is not designed for horizontally scaling/replicas. 

Even large scale severs like hypixel don’t share world data across their backend server farm. Instead they use something like bungeecord to make it feel like you’re entering one big server but their routing sends players off to numerous, distinct servers.
