### ISSUE TITLE
OpenJ9 Dockerfile unusable -XX option (+UseG1GC)

### ISSUE THREAD

**Issue by Panderine** [itzg/docker-minecraft-server#521]
https://github.com/itzg/docker-minecraft-server/blob/480b7645ba6a5cc7842ef0f232607521390a42d4/Dockerfile#L69

I was having a look at the different ENV settings and I found this dockerfile has this hard-coded. I'm still and infant in openj9 parameters but I believe this option does nothing. I'm I correct? Please disregard this issue if this has no real impact whatsoever.

Thanks!

**Comment by itzg** [comment]
Totally fair question since I'm also new to OpenJ9 (and actually still not using it that much). Speaking of which, I had forgotten that in that branch I had removed that JVM option:

https://github.com/itzg/docker-minecraft-server/commit/007f9426bf76ec4301cf187515b47609c92ba739#diff-3254677a7917c6c01f55212f86c57fbf

which results in this tag/branch specific Dockerfile

https://github.com/itzg/docker-minecraft-server/blob/openj9/Dockerfile

So, all is good, but thanks for double checking.

**Comment by Panderine** [comment]
Sorry, it's me again... so If I understood correctly you changed it in openj9 branch but not in openj9-nightly?  Nevertheless there is no real impact in having this because openj9 VM just ignores it, right?

Thanks!

**Comment by itzg** [comment]
Oops, I did miss that change in the nightly branch

https://github.com/itzg/docker-minecraft-server/blob/openj9-nightly/Dockerfile

**Comment by itzg** [comment]
There were a few changes I missed from the openj9 branch, but they're all brought over now.

**Comment by Panderine** [comment]
Thanks!!! I'm testing a lot with openj9 and having great results server side, now with nightly I finally have good results client side too.
