### ISSUE TITLE
Problem building docker image armv7

### ISSUE THREAD

**Issue by giri-v** [itzg/docker-minecraft-server#557]
Hi, I forked your repo and tried to build the armv7 branch. But the docker build fails on dockerHub

The command '/bin/sh -c easy-add --var os=${TARGETOS} --var arch=${TARGETARCH}${TARGETVARIANT} --var version=1.2.0 --var app=restify --file {{.app}} --from https://github.com/itzg/{{.app}}/releases/download/{{.version}}/{{.app}}_{{.version}}_{{.os}}_{{.arch}}.tar.gz' returned a non-zero code: 2

Any idea?

**Comment by itzg** [comment]
Docker Hub doesn't support multi-architecture builds, only x86 64-bit. At that step Docker Hub is attempting to run an armv7 executable on an x86 64-bit processor.

FYI, I have effectively deprecated the armv7 branch and instead maintain armv7 (and aarch64) support in the `multiarch` branch. FYI I now use Github actions to perform the build of `itzg/minecraft-server:multiarch`. In general though, please feel free to contribute back to this repo since I have all the image build setup already.
