### ISSUE TITLE
fix permission of libraries

### ISSUE THREAD

**Issue by Diluka** [itzg/docker-minecraft-server#559]
I download libraries in another container using root. when server start, it should fix permission of libraries before install forge

**Comment by itzg** [comment]
When does that become a problem?

**Comment by Diluka** [comment]
if all files in libraries is '644' owned by 'root', the forge install will failed. But this situation is made of proxy issue. I use `openjdk` to run `java -jar -DsocksProxyHost=... -DsocksProxyPort=... forge-installer.jar --installServer` to download `libraries`. since #415 is fixed, this should not happen again.

**Comment by itzg** [comment]
Oh, I see, the chmod logic got skipped in your case since `/data` ownership is correct but some of the contents weren't

https://github.com/itzg/docker-minecraft-server/blob/master/start#L34-L37

Do you mind if I close this issue since this workaround before #415 was fixed would have been to manually `chown` those files?

**Comment by Diluka** [comment]
ok
