### ISSUE TITLE
Starting For The First Time

### ISSUE THREAD

**Issue by itsMighty** [itzg/docker-minecraft-server#566]
I'm brand new to docker and using it on my Synology NAS. I downloaded your Minecraft image off the "Image" section but every time I start it up it keeps restarting due to not having the EULA accepted. I can't find where to add it. Thanks.

**Comment by itzg** [comment]
I haven't used Synology Diskstation myself, but looking at the docs

https://www.synology.com/en-global/knowledgebase/DSM/help/Docker/docker_container

it appears you'll go into Advanced Settings and go to the "Environment" tab. You'll also need to add port mappings in "Port Settings".

**Comment by thomashess** [comment]
I had the same issue on Synology.

Open the container settings, go to Environment tab. Add a new variable called EULA, set value to true. This will allow you to start up the container.

First time start up takes a while, because it has to generate the world. 

You can also download the server.properties file, do manual edits (to change seed etc), and then re-upload it before starting the container up.
