### ISSUE TITLE
[question] Upgrading spigot

### ISSUE THREAD

**Issue by JulienTant** [itzg/docker-minecraft-server#568]
Hi,

So let's say I install the newest version of spigot (`TYPE=spigot && VERSION=1.16.1`) and in a few days, they upgrade it. Out of the docker process we use, I would have to rebuild a jar. What's the best way to do it using docker-minecraft-server ? Should i drop the jar from my volume ? or set `FORCE_REDOWNLOAD=true` ? Or is there another way to deal with that ?

Also can i target a specific build ? like target build [118](https://hub.spigotmc.org/jenkins/job/BuildTools/118/)

I don't mind contributing with a PR to update the documentation once it's more clear to me.

**Comment by itzg** [comment]
If you leave `VERSION` set at `LATEST` it will always check for the newest Spigot version at startup and download, if needed. Otherwise, you can always recreate the container, change `VERSION`, attach the pre-existing data volume and again it will download that version as needed.

As for the specific build question, you referenced the BuildTools version. I'm pretty sure that's independent of the Spigot version.

FWIW, the pre-built Spigot and Bukkit jars are downloaded from https://getbukkit.org/, so the `LATEST` version tracking I mentioned will be subject to updates posted there.

**Comment by JulienTant** [comment]
Yeah i kinda got confused with BuildTools and the SPIGOT jar itself. Thanks!
