### ISSUE TITLE
Changing minecraft server memory allocation from 1G to 4G

### ISSUE THREAD

**Issue by Foxatron-notadev** [itzg/docker-minecraft-server#615]
I am having trouble finding a way to change the startup command for my minecraft server.

Issue
-----------

I want to change the allocated memory for the minecraft server from the default 1G of allocated memory to 4G of allocated memory (**Without** creating a new docker container)

i haven't found any post regarding how to do it. or the specific command or if it is actually possible 

your documentation on the [GitHub page](https://github.com/itzg/docker-minecraft-server#memory-limit) for the Memory Limit with an example of :-
`-e MEMORY=2G
`
can i make changes to an existing docker container without creating a new one using `docker run -d -p 25565:25565 -e MEMORY=4G --name mc -e EULA=TRUE itzg/minecraft-server`?

**IF Yes** :- 
---
What command do i have to type to pass that command to the docker container?
Could you give me an example command or a link for it?

**IF No** :-
---
is there a way to transfer the minecraft world from a local windows PC to the docker container?
Could you give me an example command or a link for it?

----------------------------------------------------------------------------------------
Sorry if it had been answered before :) 

Thx in advance

**Comment by itzg** [comment]
How did you create your current container?

**Comment by FreezyExp** [comment]
Sorry for side-tracking this issue a bit, but I think this info might help you (or others reading this).

first, check where your data is being stored, or backups
if those are secure, then changing the container is less of a problem
As you can always just redeploy a container as long as you have the data

next, I can highly recommend you use docker-compose instead of docker cli
as it allows you to make changes in a more human friendly way
Edit the docker-compose.yml file with the changes you need
then "docker-compose up -d"
(-d is for detached)

need to make another change?
docker-compose down
alter the yml again
then "docker-compose up -d"
it saves you a lot of fiddling about.

**Comment by itzg** [comment]
Great info @FreezyExp and that's exactly the line of thought I had too.

**Comment by Foxatron-notadev** [comment]
Thx @FreezyExp
