### ISSUE TITLE
Download map on existing container for new container with static /data folder

### ISSUE THREAD

**Issue by smithpet001** [itzg/docker-minecraft-server#619]
Hello! I'm new to this sort of thing :)

I have been playing on a vanilla mc server container running on my Synology device for a bit, but decided I wanted the flexibility and power of Spigot. I have been using ssh from my computer to run this image in order to set the variables right to get it to actually run (maybe that's because I'm just new, but this has been working so far). Because we have been playing on our current server for a while, we have quite a bit of progress made, but this container does not have a static /data folder where I could take the world map out easily. In fact, I have no idea where that first mc container is storing its data. I have created a new container with Spigot and a static /data folder, but how can I move the map over? Where is the map stored by default when there is no /data static folder?

My little sister and I thank you very much!

**Comment by itzg** [comment]
I'll see if I can answer all of your questions and get you switched over...

The "default" behavior actually refers to what you're calling a static volume as "anonymous volumes". Assuming your old container is named "mc", you can actually see where docker created a host directory for the anonymous volume attached at `/data` using:

```
docker container inspect -f '{{json .Mounts}}' mc
```

where my current container is reporting:
```
[{"Type":"volume","Name":"9737a456f03965e745a04886da1d936457c749132f21e5f8550b3cc4e9366350","Source":"/var/lib/docker/volumes/9737a456f03965e745a04886da1d936457c749132f21e5f8550b3cc4e9366350/_data","Destination":"/data","Driver":"local","Mode":"","RW":true,"Propagation":""}]
```

Before going further, [this documentation page on volumes](https://docs.docker.com/storage/volumes/) is a great read.

There's a couple of options but either way I'd recommend creating the new Spigot container to attach what was the old container's `/data` content at `/data` since the default world is named "world" and its data will be in the container path `/data/world`.

One option is to take the anonymous volume content and copy that to a regular directory of your choosing, such as one under your home account. With the old container stopped (assuming named "mc"), you can use:

```
docker cp mc:/data mc-data
```

Then you can create a new spigot container and attach that host directory using something like:
```
docker run ...other args... -e TYPE=SPIGOT -v ${PWD}/mc-data:/data ...
```

If you want to stick with a docker managed volume, but switch to a named volume you can run a temp container that has the old container's anonymous volume attached and a new named container ("mc-data" in this case) and copy the content:

```
docker run --rm -it --volumes-from mc -v mc-data:/mc-data alpine sh -c "cp -a /data/* /mc-data"
```

Finally, you can use a similar command but a non-path, named volume attachment:
```
docker run ...other args... -e TYPE=SPIGOT -v mc-data:/data ...
```

In either case, as you can see I'm recommending that you simply recreate your spigot container, which is not a big deal since really you're wanting to preserve your previous vanilla container's world data anyway.

There were a lot of details/topics covered there, so let me know if you have any questions from that.

**Comment by smithpet001** [comment]
Thank you so much for your fast reply. After working on this for the past hour, I seem to be just making more of a mess doing things I don't fully understand. I've now lost access to our Vanilla server completely :( It says that the port is failing to bind. I think that doesn't have to do with your instructions, but this is getting frustrating for me. I really really appreciate your time, but I'm having a hard go right now at this. We've probably only played a total of 18 hours on this world so far, so I might just ask her if we could start a new one. 

As someone who is new to this, the hardest part about reading documentation and advice is distinguishing (in code) whether something is a variable or some part of the built-in code. For example: 

`docker run ...other args... -e TYPE=SPIGOT -v ${PWD}/mc-data:/data ...`

I don't really understand whether mc-data:/data is something you've created or I have (and potentially with a slightly different path) or if it is being created now? It took me about 30 minutes last night to realize that 'path/on/host' shouldn't be typed in verbatim! Haha. I wish there were a better standard for clarifying parts of code that could be different based on each person.

Thanks again, but I might just cut my losses and start a new Spigot world. Thanks for all the work you put into this!

**Comment by itzg** [comment]
Likewise, yes, it's always a challenge to document the things that must be typed exactly versus the names of things you can make up as you want. For example "mc-data" is something I made up out of thin air. 

Definitely understandable to just start fresh with the spigot container. If you provide the output of `docker ps -a` I can take a shot at some specific commands to bring the world data over rather than making up names.
