### ISSUE TITLE
SSH into docker help

### ISSUE THREAD

**Issue by indy1172** [itzg/docker-minecraft-server#623]
Hi there. I'm running a Debian 10 server with [Simpnas](https://github.com/johnnyq/simpnas) which is more or less a NAS with docker installed. I got the Minecraft-Server docker to work.. meaning I can connect to my host IP via Majong Minecraft, and control it with the cli within docker. However I would like to be able to SSH directly into the minecraft-server cli. Could you provide any insight?

**Comment by james-d-elliott** [comment]
You need to SSH to the server where docker is installed, and run the following:

`docker exec -it <container name> /bin/bash` for example if you named your minecraft container "mc" you'd do this `docker exec -it mc /bin/bash`. If /bin/bash doesn't work, use /bin/sh.

**Comment by indy1172** [comment]
wouldnt i need to assign an alternative ssh port? I have 22 enabled for the host. Where would I assign 2222 or something else for the docker?

**Comment by itzg** [comment]
@indy1172 it's very uncommon to ssh directly into containers and besides there's not even an ssh server running within the container. Instead you do what @james-d-elliott decribed: ssh to your host and then `docker exec` into the minecraft-server container. Since you goal is probably to run server commands, more specifically you'll run `docker exec {containerName} rcon-cli {command and args}`  as described here:

https://github.com/itzg/docker-minecraft-server#interacting-with-the-server
