### ISSUE TITLE
feat: option to clear only plugins/mods inside the data directory

### ISSUE THREAD

**Issue by Silthus** [itzg/docker-minecraft-server#662]
Currently there is only the `REMOVE_OLD_MODS` flag that will clear everything inside the plugins/mods directory.

However this is not always what we want. Clearing everything would also remove configurations and flat file data, when we only need to remove old plugins that no longer exist inside the `/plugins` mount.

I am willing to do a PR on this, if ok?

**Comment by itzg** [comment]
As you may have noticed there's a twist because one of the uses blasts the entire directory as you mentioned

https://github.com/itzg/docker-minecraft-server/blob/b5c91647ca90a7ac7ea0907f90f321fc1555d884/start-finalSetupModpack#L11

but the other usage is much more precise with deletion via the rsync operation

https://github.com/itzg/docker-minecraft-server/blob/6f1f8d7806c72f45e4b5f36319565ee396a6e9dd/start-minecraftFinalSetup#L57

So, it looks like only the first one is what needs to be addressed. A PR would be great.

**Comment by Silthus** [comment]
Thanks for the links, I didnt know of the second option.

But the second option also seems to delete everything in the target that is not present in the source.

So actually we would need to add a third argument that only deletes and copies `*.jar` files, syncing them with the source.

Where should I put the methods?

Also I thought, maybe I could add a variable with an delete/sync type and keep the one boolean flag?

**Comment by itzg** [comment]
`start-utils` is probably a decent place for the new methods since it has become the shared set available pulled in both these other scripts.
