### ISSUE TITLE
How do i access the files of my server?

### ISSUE THREAD

**Issue by cperryoh** [itzg/docker-minecraft-server#730]
I was wondering how I could access the files on my server so I could load my own worlds up. I saw this command in the docs `docker run -d -v /path/on/host:/data ...` but I'm not sure how to direct it to a folder on my desktop.

**Comment by itzg** [comment]
Are you running the docker container on your desktop, such as with Docker Desktop?

Regardless, an even easier way to start out with host volumes is to use docker-compose. You would
1. Create a new, empty directory
2. Place a `docker-compose.yml` file in that directory, [like this](https://github.com/itzg/docker-minecraft-server/blob/master/examples/docker-compose-simple.yml)
3. From a terminal/command-prompt window run `docker-compose up -d` in that directory you created

That example uses a relative directory `./data` for the volume so that you can easily know that the container data volume is the `data` directory right next to the compose file. That technique works on all the platforms, Linux, Windows, MacOS.

**Comment by cperryoh** [comment]
Yeah, I ended up finding out the issue, the tutorial I was following didn't have the same path syntax as windows, I overlooked that and didn't change it 
This command did the trick:
`docker run -d -p 25565:25565 --name mc -e EULA=TRUE --restart=always -v C:\Users\cperr\Desktop\mc_server:/data itzg/minecraft-server`

**Comment by itzg** [comment]
I was guessing you were asking about Windows, which is also my primary development platform. Glad you found the full solution. Good to close the issue?
