### ISSUE TITLE
Can't connect to server through local or not local.

### ISSUE THREAD

**Issue by CleavisX** [itzg/docker-minecraft-server#761]
Hi!

I recently setup the itzg minecraft server docker on my QNAP NAS. I've gotten the server to startup and everything went smoothly. However, I cannot connect to the server using my public IP or localhost.

I'm not sure if this is a problem with my NAS settings or not.

**Comment by gundestrup** [comment]
You have to look at the docker settings for what the "external" ports are on your docker image.
I have selected fixet external port on the docker image.
Else the external docker port might change each time you restart the server.
Take a screenshot of your docker settings where port maping is visiable

**Comment by CleavisX** [comment]
> You have to look at the docker settings for what the "external" ports are on your docker image.
> I have selected fixet external port on the docker image.
> Else the external docker port might change each time you restart the server.
> Take a screenshot of your docker settings where port maping is visiable

First off, I'm using a QNAP NAS with container station to run the server.
![Capture](https://user-images.githubusercontent.com/78890653/107707777-42a5c400-6c77-11eb-9250-10c2ccc98d08.PNG)

Here is what shows when I check the docker settings. I am unsure of what the "host" section is and I assume the "container" section is the minecraft port, as its 25565. I am not sure how to set it to fixed external port.

**Comment by CleavisX** [comment]
Okay so I put the mode into bridge mode and gave it a static IP. I was able to connect locally using the IP I set it to (192.168.xx.xx) but how can I get it so people outside my network can join?

**Comment by itzg** [comment]
I would suggest deleting off the 2nd and 3rd port mappings and change the host port on the first to 25565:

![image](https://user-images.githubusercontent.com/988985/107718815-60d1eb00-6c9c-11eb-8272-d8ad91796151.png)

It's the first one you'll want to reference in your router's port forwarding and a fixed port value will be much easier to manage.

**Comment by gundestrup** [comment]
Also be carefull about an open server.
If you want to play with friends, then use whitelisting.

**Comment by JahCoby** [comment]
I have this issue currently where I can connect from any local machine but cannot connect through the public ip, or dns service, although I was able to before the docker method and simply running a server off of the windows machine. Currently the issue is happening with current docker version (everything as of 11/25/21) on currently updated Linux Mint xfce that I have running on a machine here. I have checked and double checked that the ports are forwarded from my router and did the port publishing when running the image, I have beat my head against every resource that was available but nothing suggested did anything, including trying the image again with -p for the 25565 ports, and attempting to check that docker would be listening on all hosts that was also suggested elsewhere, no dice on anything.
