### ISSUE TITLE
Please create a OpenJDK 15 (Latest)  - openj9 -  amd64 alpine permutation

### ISSUE THREAD

**Issue by Panderine** [itzg/docker-minecraft-server#794]
Thanks in advance!

**Comment by itzg** [comment]
Does it need to Alpine specifically? I'm trying to gradually migrate to the official AdoptOpenJDK base images since they are multi-architecture, but they only provide Debian based images:

https://hub.docker.com/_/adoptopenjdk?tab=tags&page=1&ordering=last_updated&name=15-openj9

FYI the Alpine base images are barely reducing the image size given all the baggage that is needed for various minecraft server types.

**Comment by Panderine** [comment]
not alpine ! sorry!. In fact I wanted to ask for AdoptOpenJDK indeed. My brain borked.

**Comment by itzg** [comment]
Both choices would have been AdoptOpenJDK distributions, but glad you were simply wanting the "other A-thing" 😊

**Comment by itzg** [comment]
`itzg/minecraft-server:java15-openj9` is now published

**Comment by Panderine** [comment]
Will test later tonight. Thanks!

**Comment by Panderine** [comment]
Worked like a charm. Thanks!

**Comment by C0Nd3Mnd** [comment]
Naming seems a bit off when the Java 11 version is called `openj9-11` and this one is now called `java15-openj9`. I don't really mind, I just noticed.
