### ISSUE TITLE
[Enhancement] Replace autopause with something like mcsleepingserverstarter

### ISSUE THREAD

**Issue by Panderine** [itzg/docker-minecraft-server#812]
This tools seems better than sleeping the process because the server is actually stopped. Freeing memory as well as CPU. 

https://github.com/vincss/mcsleepingserverstarter

**Comment by itzg** [comment]
Thanks for the suggestion, but I am hesitant to move forward with this for a few reasons:

- "Freeing memory" doesn't seem a high priority to me since Linux kernels have long since implemented virtual memory strategies. In this case, the memory "used" by a paused container/process will likely get paged out of physical memory anyway.
- The implementation linked is NodeJS based and I would prefer to not add NodeJS to the image for size reduction reasons. It took quite a while to adjust things to eliminate python from the image and would hate to take a step backward by adding back another interpreter
- I have only briefly inspected their code, but fully stopping and starting the minecraft server defeats the point of autopause since the startup time, such as loading a large modpack, would need to be incurred when the port is knocked. If fully releasing the process and its memory is a desire, then I would recommend solving that externally with some form of docker auto-scaling (such as with kubernetes) to scale down the container instances to zero. 

@Oekn5w any counter-points or thoughts you want to add?

P.S. Also keep in mind that Docker is itself a layering-paradigm, so you or anyone else is welcome to create a Docker image that is based `FROM` this image and introduces `mcsleepingserverstarter`.

**Comment by Panderine** [comment]
Well of course all your points are valid. What I was thinking when proposing this is the same use case I have on my server, I have a some spare hw that I use for my microservices. I don't play MC 24/7 and my server actually comes alive on the afternoon/night. It's nice to save that 6GB of memory for my other services. I'm in fact migrating to a k3s cluster by adding a small powered NUC to the mixture.In fact your recommendation could be a better fit for me.

**Comment by itzg** [comment]
I was thinking more later that you could actually use and run knockd similar to

https://github.com/itzg/docker-minecraft-server/tree/master/files/autopause

on your host and instead of what those scripts are doing, use docker start/stop commands to bring up the server container when needed.

**Comment by Panderine** [comment]
yes, the difference with that node.js code is that it understands mc traffic. I believe knockd resumes/starts the process with just a icmp ping to the server port. I have to read more about it, dunno if something else triggers the wake by mistake like network discovery tools or things like that, some IoT device doing some angry scanning or other tools... you shouldn't have something like that in your network... but you know...... anyway its just an edge case. Will take a dive into your suggestions. Thanks again!!

**Comment by Oekn5w** [comment]
@Panderine yes, knock sometimes reacts to these, autopause has different timeouts after knocks depending whether a connection is established or not.
