### ISSUE TITLE
[Feature Request] Preemptive logging for invalid configurations

### ISSUE THREAD

**Issue by AllanWang** [itzg/docker-minecraft-server#863]
This is an extension of https://github.com/itzg/docker-minecraft-server/issues/834#issuecomment-837673966

It seems like the default minecraft version does not support plugins, and so the spiget configs + plugins folder will be ignored. This is probably common sense for anyone after they've deployed a server, but would it be possible to log such incompatibilities to help with newcomers like myself?

From external services, I just assumed that paper was the new default, and didn't know about switching the types until it was mentioned. There may be other such scenarios where flags are silently ignored, unbeknownst to the dev

**Comment by itzg** [comment]
I fully appreciate the frustration of that scenario; however, I'll have to give this more thought since I currently support 14 types of servers where some are combinations or forms of each other. I think the practical thing I can do is emphasize the default TYPE=VANILLA in the intro section. 

I'm curious about this statement though

> From external services, I just assumed that paper was the new default

There might be some common knowledge I'm missing out on, but I had no idea Paper was considered a new default.

**Comment by AllanWang** [comment]
Oh no. I meant common message _I_ was missing out on. Most minecraft servers will default on a mod supported variant in their setup. I just assumed that defaults would support plugins, and was unaware fo the vanilla builds.

**Comment by itzg** [comment]
The default server type is now clarified in the introductory section of the README

![image](https://user-images.githubusercontent.com/988985/118066935-30feb600-b365-11eb-860e-95e74eef6df7.png)

> Most minecraft servers will default on a mod supported variant in their setup

Do you mean Minecraft server hosting providers?

**Comment by AllanWang** [comment]
Yes minecraft hosting providers. And lgtm!
